---
- name: "[📶] cloudflare-ddns"
  community.docker.docker_container:
    name: cloudflare-ddns
    hostname: cloudflare-ddns
    image: favonia/cloudflare-ddns:latest
    pull: true
    capabilities:
      - SETUID
        # Capability to change user ID; needed for using PUID
      - SETGID
        # Capability to change group ID; needed for using PGID
    cap_drop:
      - all
      # Drop all other capabilities
    read_only: true
    # Make the container filesystem read-only
    security_opts:
      - no-new-privileges:true
        # Another protection to restrict superuser privileges
    networks:
      - name: internal
    env:
      PUID: "1000"
      # Run the updater with user ID 1000
      PGID: "1000"
      # Run the updater with group ID 1000
      CF_API_TOKEN: "{{ cloudflare_apikey }}"
      # Your Cloudflare API token
      DOMAINS: "{{ cloudflare_domains | join(',') }}"
      # Your domains (separated by commas)
      PROXIED: "true"
      # Tell Cloudflare to cache webpages and hide your IP
    restart_policy: always
    state: started
