---
- name: "[HA] Container"
  community.docker.docker_container:
    name: "home-assistant"
    hostname: "home-assistant"
    image: ghcr.io/home-assistant/home-assistant:stable
    pull: true
    volumes:
      - "homeassistant_config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/run/dbus:/run/dbus:ro"
    networks:
      - name: internal
      - name: bridge
    ports:
      - "8123:8123"
    privileged: yes
    restart_policy: unless-stopped
    state: started
