---
- name: volume
  community.docker.docker_volume:
    volume_name: "influxdb_data"
- name: docker container
  community.docker.docker_container:
    name: influxdb
    hostname: influxdb
    image: influxdb:latest
    pull: true
    networks: internal
    volumes: "influxdb_data:/var/lib/influxdb"
    # ports:
    # - "8086:8086"
    # - "8089:8089/udp"
    env:
      TZ: "America/Santiago"
      INFLUXDB_HTTP_ENABLED: "true"
      INFLUX_DB: "host"
    restart_policy: unless-stopped
    state: started
# docker exec -it influxdb influx setup

- name: copy conf
  become: true
  template:
    src: influxdb.config.j2
    dest: /var/lib/docker/volumes/influxdb_data/_data/influxdb.conf
