---
- name: "[speedtest] docker container"
  community.docker.docker_container:
    name: speedtest
    hostname: speedtest
    image: ghcr.io/danopstech/speedtest_exporter:latest
    pull: true
    networks:
      - name: internal
    restart_policy: unless-stopped
    state: started
