---
- name: "[varken] volume"
  community.docker.docker_volume:
    volume_name: "varken_data"
- name: "[varken] docker container"
  community.docker.docker_container:
    name: varken
    hostname: varken
    image: boerderij/varken:latest
    pull: true
    networks:
      - name: internal
    volumes:
      - "varken_data:/config"
    env:
      TZ: "America/Santiago"
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped
    state: started
