---
- name: "[scale]"
  block:
    - name: check if we're in arch
      stat:
        path: /etc/arch-release
      register: arch_release
    - name: "[🔅] arch install"
      become: true
      block:
        - name: pacman
          community.general.pacman:
            name:
              - "tailscale"
            state: present
        - name: enable service
          systemd:
            name: tailscaled
            enabled: yes
            state: started
      when: arch_release.stat.exists
    # - name: container
    #   community.docker.docker_container:
    #     name: tailscale
    #     hostname: tailscale
    #     image: tailscale/tailscale:latest
    #     pull: true
    #     networks:
    #       - name: internal
    #     volumes:
    #       - "tailscale:/var/lib"
    #       - "/dev/net/tun:/dev/net/tun"
    #     capabilities: # Required for tailscale to work
    #       - "net_admin"
    #       - "sys_module"
    #     env:
    #       TS_EXTRA_ARGS: "—ssh"
    #       TS_HOSTNAME: "mocha"
    #       TS_USERSPACE: "false"
    #     command: tailscaled
    #     privileged: true
    #     restart_policy: unless-stopped
    #     state: started
    # - name: container
    #   community.docker.docker_container:
    #     name: tailscale
    #     hostname: tailscale
    #     image: headscale:latest
    #     pull: true
    #     networks:
    #       - name: internal
    #     ports:
    #       - "8043:8043"
    #     security_opts:
    #       - no-new-privileges:true
    #     volumes:
    #       - "headscale:/etc/headscale"
    #       - "headscale_data:/var/lib/headscale"
    #     env:
    #       TZ: "America/Santiago"
    #     command: "headscale serve"
    #     restart_policy: unless-stopped
    #     state: started

    # - name: webui
    #   community.docker.docker_container:
    #     name: tailscale-webui
    #     hostname: tailscale-webui
    #     image: ghcr.io/gurucomputing/headscale-ui:latest
    #     pull: true
    #     networks:
    #       - name: internal
    #     ports:
    #       - "8080:8080"
    #     security_opts:
    #       - no-new-privileges:true
    #     env:
    #       TZ: "America/Santiago"
    #     restart_policy: unless-stopped
    #     state: started
