---
- name: cron | copy script
  become: true
  ansible.builtin.template:
    src: crontasks.j2
    dest: /home/ansible/cron.sh
    owner: ansible
    group: ansible
    mode: 0755

- name: cron | Notify webhook on server reboot
  become: true
  become_user: root
  ansible.builtin.cron:
    name: "Notify webhook on server reboot"
    state: present
    special_time: "reboot"
    job: "/home/ansible/cron.sh {{ webhook_url }}"
# curl -X POST -H "Content-Type: application/json" -d "{{lookup("template", "restart.j2")}}"
