---
- name: "Create promtail-config.yml"
  become: true
  template:
    src: promtail-config.yml.j2
    dest: /etc/promtail-config.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart promtail

- name: "Create loki-config.yml"
  become: true
  template:
    src: loki-config.yml.j2
    dest: /etc/loki-config.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart loki

- name: "[Promtail] loki container"
  community.docker.docker_container:
    name: loki
    hostname: loki
    image: grafana/loki:latest
    restart_policy: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - loki:/loki
      - /etc/loki-config.yml:/etc/loki-config.yml
    command:
      - "-config.file=/etc/loki-config.yml"
    networks:
      - name: internal
    state: started

- name: "[Promtail] container"
  community.docker.docker_container:
    name: promtail
    hostname: promtail
    image: grafana/promtail:latest
    restart_policy: unless-stopped
    volumes:
      - minecraft_data:/var/log/minecraft:ro
      - /etc/promtail-config.yml:/etc/promtail-config.yml:ro
    command:
      - "-config.file=/etc/promtail-config.yml"
    networks:
      - name: internal
    state: started
