---
- name: "[🔅] 4get"
  community.docker.docker_container:
    name: 4get
    hostname: 4get
    image: tarobubbletea/4get:latest
    pull: true
    networks:
      - name: internal
    published_ports:
      - "880:80" #left port is local only anyway

    env:
      FOURGET_VERSION: "6"
      FOURGET_SERVER_NAME: "bunsearx"
      FOURGET_SERVER_ADMIN_EMAIL: "bun@{{host_tld}}"
      FOURGET_SERVER_SHORT_DESCRIPTION: "Nothing's working out"
      FOURGET_SERVER_LONG_DESCRIPTION: "aHR0cHM6Ly9yZW50cnkuY28vYUdpZnRGcm9tX1NDSEFMRQ=="

    volumes:
      # - /etc/letsencrypt/live/domain.tld:/etc/4get/certs
      - fourget:/var/www/html/4get
      - fourget_apache:/etc/apache2

    labels:
      traefik.enable: "true" #supposed to be a string for some reason???
      traefik.http.services.fourget.loadbalancer.server.port: "80"
      traefik.http.routers.fourget.rule: Host(`{{url}}`)
      traefik.http.routers.fourget.entrypoints: web

    restart_policy: unless-stopped
    state: started

- name: copy all files over
  become: true
  block:
    # - name: find banners
    #   find:
    #     paths: banners/
    #     patterns: "*.png"
    #     use_regex: no
    #   register: fourget_banners
    - name: banners
      copy:
        src: banners/
        dest: /var/lib/docker/volumes/fourget/_data/banner/
    - name: delete default banner
      file:
        path: /var/lib/docker/volumes/fourget/_data/banner/4get-default.png
        state: absent
    - name: copy theme
      copy:
        src: spigot.css
        dest: /var/lib/docker/volumes/fourget/_data/static/themes/spigot.css
    - name: set theme
      replace:
        path: /var/lib/docker/volumes/fourget/_data/data/config.php
        regexp: 'const DEFAULT_THEME = "(.+)";$'
        replace: 'const DEFAULT_THEME = "spigot";'
    - name: favicon
      copy:
        src: favicon.ico
        dest: /var/lib/docker/volumes/fourget/_data/
    # - name: conf
    #   template:
    #     src: config.php.j2
    #     dest: /var/lib/docker/volumes/fourget/_data/data/
    # - name: apache conf
    #   #on every restart it keeps breaking apparently?
    #   template:
    #     src: httpd.conf.j2
    #     dest: /var/lib/docker/volumes/fourget_apache/_data/httpd.conf
    # - name: copy certs # bug was fixed
    #   copy:
    #     src: /etc/letsencrypt/live/nanachi.store/
    #     dest: /var/lib/docker/volumes/fourget/_data/certs/
