---
- name: "[🔅] 4get volume"
  community.docker.docker_volume:
    volume_name: "fourget"

- name: "[🔅] 4get"
  community.docker.docker_container:
    name: 4get
    hostname: "{ { container_name } }"
    image: luuul/4get:latest
    pull: true
    networks:
      - name: internal
    published_ports:
      - "61201:80"

    env:
      - FOURGET_SERVER_NAME=find.nanachi.store
      - FOURGET_SERVER_ADMIN_EMAIL="veryillegalusername@gmail.com"

    volumes:
      # - /etc/letsencrypt/live/domain.tld:/etc/4get/certs
      - fourget/banner:/var/www/html/4get/banner
      - fourget/captcha:/var/www/html/4get/data/captcha
      - fourget/icons:/var/www/html/4get/icons
      - fourget/themes:/var/www/html/4get/static/themes
      - fourget/favicon.ico:/var/www/html/4get/favicon.ico
      - fourget/data:/var/www/html/4get/data

    labels:
      traefik.enable: true
      traefik.port: "61201"
      traefik.http.routers.fourget.rule: "Host(`{{ url }}`)"

    restart_policy: unless-stopped
    state: started
