---
- name: "[📶] internal network"
  community.docker.docker_network:
    name: internal
    state: present

- name: "[📶] Traefik volume"
  community.docker.docker_volume:
    volume_name: "traefik_data"

- name: "[📶] Traefik"
  community.docker.docker_container:
    name: traefik
    hostname: traefik
    image: "traefik:v2.10"
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_data:/etc/traefik"
    networks:
      - name: internal
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      TRAEFIK_API: true
      TRAEFIK_API_DASHBOARD: true
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: internal
    restart_policy: unless-stopped
    status: started
