---
- name: "[📶] cloudflared-web"
  community.docker.docker_container:
    name: cloudflared-web
    hostname: cloudflared-web
    image: wisdomsky/cloudflared-web
    pull: true
    networks:
      - name: internal
    restart_policy: unless-stopped
    state: started
    ports:
      - "14333:14333"
    # won't be exposing this management page to the wide network / no traefik settings here

- name: debug msg
  debug:
    msg: "---- REMINDER ---- cloudflared-web is running at localhost:14333"
