---
- name: Create a volume for Nginx Proxy Manager
  community.general.docker_volume:
    volume_name: "nginxpm_data"

- name: Create a volume for Letsencrypt
  community.general.docker_volume:
    volume_name: "letsencrypt"

- name: Deploy nginxproxymanager container
  community.docker.docker_container:
    name: nginxproxymanager
    hostname: "{ { container_name } }"
    image: "jc21/nginx-proxy-manager:latest"
    pull: true
    volumes:
      - "nginxpm_data:/data"
      - "letsencrypt:/etc/letsencrypt"
    networks:
      - name: internal
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    restart_policy: unless-stopped
    state: started
# - name: fix permissions
#   shell: docker exec nginxproxymanager chown -R 777:777 /data

# - name: chmod 777
#   shell: docker exec nginxproxymanager chmod -R 777 /data
