---
- name: "[telegraf] Get docker.sock group ID"
  command: stat -c '%g' /var/run/docker.sock
  register: docker_sock_gid
- name: "[telegraf] volume"
  community.docker.docker_volume:
    volume_name: "telegraf_data"
- name: "[telegraf] docker container"
  community.docker.docker_container:
    name: telegraf
    hostname: telegraf
    image: telegraf:latest
    pull: true
    #some update forced the container to run as user so now we do what we gotta do,,
    user: "telegraf:{{ docker_sock_gid.stdout }}"
    networks:
      - name: internal
      - name: bridge
    security_opts:
      - no-new-privileges:true
    volumes:
      - "telegraf_data:/etc/telegraf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys:/rootfs/sys:ro"
      - "/proc:/rootfs/proc:ro"
      - "/etc:/rootfs/etc:ro"
    env:
      TZ: "America/Santiago"
      HOST_PROC: "/rootfs/proc"
      HOST_SYS: "/rootfs/sys"
      HOST_ETC: "/rootfs/etc"
      #need to get influx_token with the webui
    restart_policy: unless-stopped
    state: started
# docker exec -it influxdb influx setup

- name: "[telegraf] copy conf"
  become: true
  template:
    src: telegraf.conf.j2
    dest: /var/lib/docker/volumes/telegraf_data/_data/telegraf.conf
