---
- name: abort if not running on Debian
  fail:
    msg: "This role is only for Debian"
  when: ansible_distribution != 'Debian'

- name: install stuff
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - git
    - curl
    - unzip
    - wget
    - zip
    - fish
  when: "ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'"
