---
- name: user | Make user {{ main_user }}
  become: true
  register: user_created
  ansible.builtin.user:
    name: { { main_user } }
    shell: { { main_shell } }
    password: "{{ main_password | password_hash('sha512') }}"
    update_password: on_create
    group: sudo
    append: true
    state: present

- name: user | SSH directory on {{ main_user }}
  become: true
  ansible.builtin.file:
    mode: "0700"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    path: "{{ user_created.home }}/.ssh"
    state: directory

- name: user | Add local SSH pubkey into {{ main_user }}
  become: true
  ansible.posix.authorized_key:
    user: "{{ main_user }}"
    state: present
    key: "{{ pubkey }}"

- name: user | No password sudo
  become: true
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ main_user }}
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
