---
- name: read local ssh pubkey
  delegate_to: localhost
  ansible.builtin.shell: cat ~/.ssh/id_rsa.pub
  register: pubkey

- name: "[Setup]"
  include_tasks: setup.yml

# already created user in the system with debian installer
- name: "[Custom user]"
  include_tasks: custom_user.yml

- name: "[Cron jobs]"
  include_tasks: crons.yml
