---
- name: user | Make user {{ ansible_user }}
  remote_user: root
  register: user_created
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    password: "{{ ansible_password | password_hash('sha512') }}"
    update_password: on_create
    group: sudo
    append: true
    state: present

- name: user | SSH directory on {{ ansible_user }}
  remote_user: root
  ansible.builtin.file:
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    path: "{{ user_created.home }}/.ssh"
    state: directory

- name: user | Add local SSH pubkey into {{ ansible_user }}
  remote_user: root
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ pubkey }}"

- name: user | No password sudo
  remote_user: root
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ ansible_user }}
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
