---
- name: debian tasks for docker
  become: true
  block:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

    - name: Install dependency for docker
      ansible.builtin.apt:
        name: "{{ docker_deps }}"
        state: present
        update_cache: true

    - name: Add GPG key for Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
        state: present

    - name: Install docker
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: true
      notify:
        - start docker

    - name: Ensure group docker exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add users to docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups:
          - docker
        append: true
      loop:
        - "{{ username }}"
        - "{{ ansible_user }}"

    # - name: Install Python docker dependency
    #   ansible.builtin.pip:
    #     name: docker
    #     state: present

    - name: Make sure that the docker folders exists
      ansible.builtin.file:
        path: "{{ docker_dir }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
        state: directory

    - name: Make internal docker network
      community.general.docker_network:
        name: internal
        state: present
